Montevideo/src/objects/Coupon__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SurveyAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurveyAnswer</label>
        <referenceTo>SurveyAnswer__c</referenceTo>
        <relationshipLabel>Coupons</relationshipLabel>
        <relationshipName>Coupons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Coupon Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SurveyAnswer</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>SurveyAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Montevideo/src/classes/DashboardController.cls
public with sharing class DashboardController extends CustomController{
    
    public String code {get;set;}
    
    public List<Coupon__c> lastCoupons{get;set;}
    
    
    public DashboardController(){
        super();
        String pageName = Util.getCurrentPageName();
        if (!Util.checkPermissions(pageName, role.Name)){
            Util.goToError();
        }
        
        lastCoupons = [SELECT Name,SurveyAnswer__r.Survey__r.Name, Available__c, Discount__c FROM Coupon__c];
    }
    
    
    public PageReference goToSurvey() {
        
        List<SurveyAnswer__c> surveyAnswer = [SELECT Code__c
        FROM SurveyAnswer__c 
        WHERE Code__c = :code and CustomUser__r.Username__c = :user.Username__c];
                        
        if(surveyAnswer.size() > 0)
        {
            Pagereference completesurvey = Page.CompleteSurvey;
            completesurvey.getParameters().put('code',code);
            completesurvey.setRedirect(true);
            return completesurvey; 
        }
        else{
            Message = 'There is no survey for this code and user!';
            showErrorMessage = true;
            showMessage = true;
        }
        return new PageReference( '/apex/Dashboard');
    }
    
    public PageReference logout(){
   		CookieManager.logout();
   		PageReference login = Page.CustomLogin;
        login.setRedirect(true);
        return login;
   	}      
}