Montevideo/src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <label>Logo Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Montevideo/src/classes/CommerceProfileControllerTest.cls
@isTest
private class CommerceProfileControllerTest{

    static testMethod void verifySetCurrentShop(){
    Shop__c shop1 = new Shop__c(Name='Shop1');
    Shop__c shop2 = new Shop__c(Name='Shop2');
    Shop__c shop3 = new Shop__c(Name='Shop3');
    test.startTest();
    insert shop1;
    insert shop2;
    insert shop3;
    test.stopTest();
    Shop__c retrievedShop = [SELECT Name, Site__c, Logo_Url__c FROM Shop__c WHERE Id = :shop2.Id];
    CommerceProfileController controllerToBeTested = new CommerceProfileController();
    controllerToBeTested.shopIdChosen = shop2.Id;
    controllerToBeTested.SetCurrentShop();
    System.AssertEquals(controllerToBeTested.currentShop.Id,shop2.Id);
    }

}