src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Montevideo/src/objects/Option__c.object
    <fields>
        <fullName>Survey__c</fullName>
        <formula>CASESAFEID(Question__r.Survey__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey</label>
        <type>Text</type>
    </fields>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shop__c.object
<CustomObject>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Montevideo/src/objects/Shop__c.object
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Shops</relationshipLabel>
        <relationshipName>Shops</relationshipName>
        <type>Lookup</type>
    </fields>

Montevideo/src/objects/Shop__c.object
    <fields>
        <fullName>Custom_User_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Owner</label>
        <referenceTo>CustomUser__c</referenceTo>
        <relationshipLabel>Shops</relationshipLabel>
        <relationshipName>Shops</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Shop__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop</label>
        <referenceTo>Shop__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateSurveyController.cls
public with sharing class CreateSurveyController extends CustomController {

    public PageReference changeType() {
        return null;
    }


    public Survey__c survey {get; set;}
    public List<Question> QuestionsInSurvey {get; set;}
    public Shop__c shop {get; set;}
    
    public String currentQuestionText {get; set;}
    public Integer CurrentQuestionNumber {get; set;}    
    public String currentQuestionType {get; set;}
    public String currentOptionText {get; set;}
    
    public List<Option> OptionsListAux{get; set;}
       
    public List<SelectOption> getQuestionTypes() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('Text','Text')); 
        options.add(new SelectOption('Radio','Radio')); 
        options.add(new SelectOption('Checkbox','Checkbox')); 
        return options; 
    }
    
    public CreateSurveyController()
    {
    	survey = new Survey__c();
    	QuestionsInSurvey = new List<Question>();   
        OptionsListAux = new List<Option>(); 
        currentQuestionType = 'Text';  
               
        if(user!=null){
         	List<Shop__c> userShop = [SELECT Category__c, Id, Name
	        FROM Shop__c 
	        WHERE Custom_User_Owner__c = :user.Id];
	        if(userShop.size() > 0)
		     {
		        	 shop = userShop.get(0);
		     }
	   	}
        
       
         
    }
    
    public PageReference AddQuestion()
    {
        Question newQuestion = new Question();
        newQuestion.Text = currentQuestionText;
        newQuestion.Type = currentQuestionType;
        newQuestion.QuestionNumber = QuestionsInSurvey.size() + 1; 
        newQuestion.QuestionOptions = new List<Option>(); 
        CurrentQuestionNumber = newQuestion.QuestionNumber;
        for (Option op : OptionsListAux){
            newQuestion.QuestionOptions.Add(op);
        }
        QuestionsInSurvey.Add(newQuestion);
        return null;
    }
    
    public PageReference AddOption()
    {
        Option newOption = new Option();
        newOption.Text = currentOptionText;
        OptionsListAux.add(newOption);
        return null;
    }
    
    public PageReference AddSurvey()
    {
    	
    	survey.Shop__c = shop.Id;
        Insert survey;
        for(Question q: QuestionsInSurvey){
        Question__c newQuestion = new Question__c();
        newQuestion.Text__c = q.Text;
        newQuestion.Type__c = q.Type;
        newQuestion.Survey__c = survey.Id;
        Insert newQuestion;
             for(Option op: q.QuestionOptions){      
              Option__c newOption = new Option__c();
              newOption.Text__c = q.Text;
              newOption.Question__c = newQuestion.Id; 
              Insert newOption;
            }
        }
        
        return null;
                
    }
 class Question {
    public String Text {get; set;}
    public Integer QuestionNumber {get; set;}
    public List<Option> QuestionOptions {get; set;}
    public String Type {get; set;}
        
     // myInnerClass code here
   }
   
   class Option {
     public String Text {get; set;}
   }
   
}