src/objects/Coupon__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateUsed__c</fullName>
        <label>DateUsed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SurveyAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurveyAnswer</label>
        <referenceTo>SurveyAnswer__c</referenceTo>
        <relationshipLabel>Coupons</relationshipLabel>
        <relationshipName>Coupons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SurveyAnswer</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>SurveyAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditCouponController.cls
public with sharing class EditCouponController {

    public Coupon__c coupon {get; set;}
    public String code {get; set;}
    
    public EditCouponController(){
        
    }
    
    public PageReference findCoupon(){
        
        List<Coupon__c> couponList = [SELECT Code__c, DateUsed__c, Discount__c, SurveyAnswer__r.Id, Available__c From Coupon__c Where Code__c=: code];
        if (couponList.size()>0){
            coupon = couponList.get(0);
        }else{
            //Display error message
        }
        return null;
    }
    
    public PageReference save(){
        
        upsert coupon;
        return null;
    }

}