src/objects/Coupon__c.object
<CustomObject>
    <fields>
        <fullName>SurveyAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurveyAnswer</label>
        <referenceTo>SurveyAnswer__c</referenceTo>
        <relationshipLabel>Coupons</relationshipLabel>
        <relationshipName>Coupons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DNIUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SurveyAnswer</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>SurveyAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>DNI__c</fullName>
        <label>DNI</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserShopJunt__c.object
<CustomObject>
    <fields>
        <fullName>Shop__c</fullName>
        <label>Shop</label>
        <referenceTo>Shop__c</referenceTo>
        <relationshipLabel>UserShopJunctions</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>UserRelation</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UserShopJunction</label>
    <nameField>
        <label>UserShopJunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserShopJunctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Medellin/src/classes/ComerceController.cls
public with sharing class ComerceController {
	
	public List<Shop__c> shops{get;set;}
	
	public ComerceController() {
		
		ID userId = [SELECT u.id FROM User__c  u WHERE u.DNI__c = 15962144 ].get(0).id;		
		shops = [SELECT s.Id,s.Logo__c,s.Name,s.Description__c,s.URL__c FROM Shop__c s WHERE	
					s.Id in ( SELECT us.Shop__c	FROM UserShopJunt__c us	WHERE us.User__c = :userId)];

	}

	/*
	*return the avg of percent of discount from coupon object for the 8 weeeks ago	
	*/
	public List<DataSource> getAVGCoupon(){
		  
		String shopID = Apexpages.currentPage().getParameters().get('ShopId');
		String userId = Apexpages.currentPage().getParameters().get('userId');

		if(shopID == null || userId == null){
			return null;
		}

		userId = 'a0CJ000000HjsmYMAR';
		
		List<DataSource> avgCouponPercent = new List<DataSource>();

		Integer daysAgoI = 0;	
		Integer daysAgoF = 7;			

		for(Integer i = 1; i <= 8; i++){
			
			if( i > 1 ){
				daysAgoI = daysAgoF;	
				daysAgoF *= i;
			}
			
			LIST<AggregateResult> result = Database.query('SELECT AVG(c.Disccount__c)'+
					'FROM Coupon__c c '+
					'WHERE '+
 						'c.Id in (	SELECT s.Coupon__c '+
									'FROM SurveyAnswer__C s '+
									'WHERE '+
										's.DNIUser__c = :userId) '+
						'AND c.status__c = \'Used\' '+
						'AND c.date_of_use__c >= N_DAYS_AGO:'+daysAgoF+
						' AND c.date_of_use__c <= N_DAYS_AGO:'+daysAgoI );

			
			String label = 'Week '+i;
			
			if(result !=null && result.size() > 0){
				
				if(result.get(0).get('expr0')!=null){					
					Double val = Double.valueOf(result.get(0).get('expr0'));
					avgCouponPercent.add(new DataSource(label,val));
				}else{
					avgCouponPercent.add(new DataSource(label,0));		
				}
				
			}else{
				avgCouponPercent.add(new DataSource(label,0));	
			}						
		}
        return avgCouponPercent;
	}

	public PageReference showShop(){
		this.getAVGCoupon();
		return null;
	}

    
     public List<PieWedgeData> getDiscountMotives() {
        List<PieWedgeData> data = new List<PieWedgeData>();
        data.add(new PieWedgeData('Jan', 30));
        data.add(new PieWedgeData('Feb', 15));
        data.add(new PieWedgeData('Mar', 10));
        data.add(new PieWedgeData('Apr', 20));
        data.add(new PieWedgeData('May', 20));
        data.add(new PieWedgeData('Jun', 5));
        return data;
    }

    // Wrapper class
    public class PieWedgeData {

        public String name { get; set; }
        public Integer data { get; set; }

        public PieWedgeData(String name, Integer data) {
            this.name = name;
            this.data = data;
        }
    }
    
	public class DataSource{
		
		public String 	lvl	{get;set;}
		public Double 	val {get;set;}		

		public DataSource(String lvl,Double val){
			this.lvl = lvl;
			this.val = val;
		}
	}
}