src/objects/Coupon__c.object
<CustomObject>
    <fields>
        <fullName>SurveyAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurveyAnswer</label>
        <referenceTo>SurveyAnswer__c</referenceTo>
        <relationshipLabel>Coupons</relationshipLabel>
        <relationshipName>Coupons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DNIUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SurveyAnswer</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>SurveyAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>DNI__c</fullName>
        <label>DNI</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Medellin/src/classes/GoToTheSurveyController.cls
public class GoToTheSurveyController {
	
	public GoToTheSurveyController(){
	}
	
	public String code{get;set;}
	public double DNI{get;set;}
	public Coupon__c coupon{get;set;}
	public SurveyAnswer__c surveyAnswer{get;set;}
	
	
	public boolean couponExist(){
		list<Coupon__c> couponList =  [SELECT c.Id, c.Name FROM Coupon__c c WHERE c.Name = :code];

		
		if(couponList != null && couponList.size() > 0 ){
			coupon = couponList.get(0);
			return true;
		}
		return false;
	}
	
	public boolean existRelationship(){
		surveyAnswer = [SELECT  s.DNIUser__c,  s.Coupon__c,s.DNIUser__r.DNI__c, s.Survey__c FROM SurveyAnswer__c s WHERE s.Coupon__c in ( SELECT c.Id FROM Coupon__c c WHERE c.Id = :coupon.Id)].get(0);

		if(null != surveyAnswer.DNIUser__c){
			return true;
		}
		return false;
	}

	public boolean thisUserIsTheOwer(){

		if(surveyAnswer.DNIUser__r.DNI__c == DNI){
			return true;
		}
		return false;
	}

	public boolean createRelationship(){

		User__c  user = [SELECT Id, User__c.Email__c, User__c.Password__c FROM User__c WHERE User__c.DNI__c = :DNI  LIMIT 1].get(0); 
		surveyAnswer.DNIUser__c = user.Id;

		try{
				update(surveyAnswer);
				return true;

			} catch(Exception e){
				return false;
			}

		return false;
	}

	public PageReference goToTheSurvey() {
		
		if(!couponExist()) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'This survey does not exist !!');
        	ApexPages.addMessage(msg);
			return null;
		}
		
		if(existRelationship()){
			
			if(!thisUserIsTheOwer()){
				ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You cann´t complete this survey !!');
	        	ApexPages.addMessage(msg);
				return null;
			}

		} else {

				if(!createRelationship()){
				ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'A error has ocurred, please try later !!');
	        	ApexPages.addMessage(msg);
				return null;
			}
		}
		
		

		String fullURL = '/apex/ApplySurvey';
		PageReference reference = new PageReference(fullURL);
		reference.getParameters().put('surveyAnswerId',surveyAnswer.Id);
        reference.setRedirect(true);
        return reference;
	
	 }

}