src/objects/CustomRole__c.object
<CustomObject>
    <label>CustomRole</label>
    <nameField>
        <label>CustomRole Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomRoles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CustomUser__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User role</description>
        <label>CustomRole</label>
        <referenceTo>CustomRole__c</referenceTo>
        <relationshipLabel>CustomUsers</relationshipLabel>
        <relationshipName>CustomUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Time__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Session Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CustomUser</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomController.cls
global abstract with sharing class CustomController {

  	global CustomUser__C user{get;set;}
  	global Boolean showErrorMessage{get;set;}
  	global Boolean showMessage{get;set;}
  	global String Message{get;set;}
  	public CustomRole__c role {get; set;}
  	
  	global CustomController () 
  	{
  		Id userId = CookieManager.getLoggedUser();
  		if (userId != null){
  			user = [SELECT Name, Username__c, First_Name__c, Last_Name__c, Role__r.Id, Email__c, Password__c, Role__r.Name, Session_Time__c
            		FROM CustomUser__c 
            		WHERE Id = :userId LIMIT 100];
            
            Id roleId = user.Role__r.Id;  
          	List<CustomRole__c> roleList = [SELECT Name FROM CustomRole__c WHERE Id = :roleId LIMIT 100];
          	if (roleList.size() > 0){
          		role = roleList.get(0);
          		CookieManager.createCookie(userId, Integer.valueOf(user.Session_Time__c));
          	}
        
  		}else{
  			Message = 'Invalid User and Password.!';
           	showErrorMessage = true;
       		showMessage = true;
  		} 	
   	}
   	
   	global PageReference getCheckPermissions(){
        String page = Util.getCurrentPageName();
      	if (!Util.checkPermissions(page, role.Name)){
        	return Util.goToError();
        }
        return null;
    }
   	
}