src/objects/CustomUser__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CustomUser</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomUserController.cls
public class CustomUserController {

    public PageReference save() {
    
        String inputString = customUser.Password__c;
        String md5Coded = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(inputString)));
        customUser.Password__c = md5Coded ;
        Insert customUser;
        return new PageReference( '/apex/CustomLogin'); 
    }
    
    
    public CustomUser__c customUser {
    get {
      if (customUser == null)
      {
        customUser = new CustomUser__c();
      }
      return customUser ;
    }
    set;
  }
    
}