src/objects/CustomUser__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CustomUser</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Shop__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shop</label>
        <referenceTo>Shop__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyAnswers</relationshipLabel>
        <relationshipName>SurveyAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SurveyAnswer</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>SurveyAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyAnswers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CompleteSurveyController.cls
public with sharing class CompleteSurveyController {

	public CustomUser__c customUser {get; set;}
	public Survey__c survey {get; set;}
	public String code {get; set;}
	
	public CompleteSurveyController(){
		
		code = ApexPages.currentPage().getParameters().get('code');
	
		List<SurveyAnswer__c> result = [select Id, CustomUser__r.Id, Survey__r.Id from SurveyAnswer__c WHERE Code__c =: code];
		if (result.size() > 0){
			//Get surveyAnswer
			SurveyAnswer__c surveyAnswer = result.get(0);
			
			//Get customUser
			List<CustomUser__c> usersList = [select Id, First_Name__c, Last_Name__c from CustomUser__c WHERE Id =: surveyAnswer.CustomUser__r.Id];
			if (usersList.size() > 0){
				customUser = usersList.get(0);
			}
			
			//Get survey
			List<Survey__c> surveyList = [select Id, Description__c, Discount__c, Shop__r.Id from Survey__c WHERE Id =: surveyAnswer.Survey__r.Id];
			if (surveyList.size() > 0){
				survey = surveyList.get(0);
			}
		}
		
	}	

}