src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Count_Number__c</fullName>
        <label>Employee Count Number</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Agroindustria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alimento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contrucción</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tecnología</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Sector__c</controllingField>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aereo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marítimo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Lechera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Avicola</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ShopEditControllerTest.cls
@isTest private with sharing class ShopEditControllerTest {

	private static void SetupShop()
	{
		Shop__c Shop = new Shop__c();
		Shop.name = 'TempShop'; 
		Shop.URL__c = 'http://www.TempShop.com'; 
		Shop.Employee_Count_Number__c = 5; 
		Shop.Description__c  = 'TempShop'; 	
		Shop.Sector__c       = 'Manufactura';
		Shop.Sub_Category__c = 'Celular';

		Database.insert(Shop);
		ApexPages.currentPage().getParameters().put('id',Shop.id);

	}
	
	@isTest public static void TestEditShopObject()
	{
		// Setup
		System.test.startTest();
		SetupShop();
		ShopEditController ShopController = new ShopEditController();
		 
		Shop__c TestResult = ShopController.getShop();

		//Execute
  
		if(TestResult != null){

			ShopController.Description = 'Edited Description';
			ShopController.UpdateShop();
			TestResult = ShopController.getShop();
		}

		ShopController.Cancel();

		System.test.stopTest();

		//Verify
		system.assertEquals(TestResult.Description__c, 'Edited Description', 'Test must update a description for a Shop object');
	}
	
	@isTest public static void TestGetSectorOptions()
	{
		// Setup
		System.test.startTest();
		SetupShop();
		ShopEditController ShopController = new ShopEditController();
		ShopController.getShop();
		ApexPages.currentPage().getParameters().put('UpdateSector','Tecnología');
		ShopController.UpdateSector();

		//Execute
		List<SelectOption> TestResult = new List<SelectOption>();
		TestResult = ShopController.getSectorOptions();


		System.test.stopTest();

		//Verify
		system.assertEquals(TestResult.isEmpty(), false, 'Test must return values from Sector List');

	}
	
	@isTest public static void TestGetSubCategoryOptionsWithout_SelectedSector()
	{
		// Setup
		System.test.startTest();
		SetupShop();

		ShopEditController ShopController = new ShopEditController();
		ShopController.getShop();

		//ApexPages.currentPage().getParameters().put('UpdateSector'     ,'Manufactura');
		ApexPages.currentPage().getParameters().put('UpdateSubCategory','Celular');
		ShopController.UpdateSector();
		ShopController.UpdateSubCategory();

		//Execute
		List<SelectOption> Sector     = new List<SelectOption>();
		List<SelectOption> TestResult = new List<SelectOption>();
		Sector     = ShopController.getSectorOptions();
		TestResult = ShopController.getSub_CategoryOptions();

		System.test.stopTest();

		system.debug('Sector.Size():'+Sector.Size());
		system.debug('TestResult.Size():'+TestResult.Size());

		//Verify
		system.assertEquals(TestResult.Size(), 1, 'Test must return values from Sub Category List');

	}
	
	@isTest public static void TestGetSubCategoryOptionsWith_SelectedSector()
	{
		// Setup
		System.test.startTest();
		SetupShop();

		ShopEditController ShopController = new ShopEditController();
		ShopController.getShop();

		ApexPages.currentPage().getParameters().put('UpdateSector'     ,'Manufactura');
		ApexPages.currentPage().getParameters().put('UpdateSubCategory','Celular');
		ShopController.UpdateSector();
		ShopController.UpdateSubCategory();

		//Execute
		List<SelectOption> Sector     = new List<SelectOption>();
		List<SelectOption> TestResult = new List<SelectOption>();
		Sector     = ShopController.getSectorOptions();
		TestResult = ShopController.getSub_CategoryOptions();

		System.test.stopTest();

		//Verify
		system.assertEquals(TestResult.isEmpty(), false, 'Test must return values from Sub Category List');

	}
	
}