src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Count_Number__c</fullName>
        <label>Employee Count Number</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Agroindustria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alimento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contrucción</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tecnología</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Sector__c</controllingField>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aereo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marítimo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Lechera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Avicola</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>DNI__c</fullName>
        <label>DNI</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserShopJunt__c.object
<CustomObject>
    <fields>
        <fullName>Shop__c</fullName>
        <label>Shop</label>
        <referenceTo>Shop__c</referenceTo>
        <relationshipLabel>UserShopJunctions</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>UserRelation</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UserShopJunction</label>
    <nameField>
        <label>UserShopJunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserShopJunctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ComerceControllerTest.cls
@isTest
public class ComerceControllerTest {
	
	@isTest static void test_existShopsForUser() {
		
		System.test.startTest();
		ComerceControllerDataProvider provider = new ComerceControllerDataProvider();
		User__c user = provider.fillUser(15962142,'frindex@gmail.com','15962142', 'franco', 'ballesteros');
		Shop__c shop = provider.fillShop('nike','shoes and sport','url to logo','www.nike.com','any sector','subcategory');
		provider.fillUserShopJunt(user,shop);

		ComerceController comerce = new ComerceController();
		List<Shop__c> shops = comerce.getShops(user.Id);
		System.test.stopTest();

		System.assert(!shops.isEmpty(),'The method getShops must be return at lest a one shop for the user.');	
	}
	

	public class ComerceControllerDataProvider{

		public User__c fillUser(Decimal dni,String email,String pass,String firstName,String lastName){

			User__c u = new User__c();
	        u.DNI__c = dni;
	        u.Email__c = email;
	        u.First_Name__c = firstName;
	        u.Last_Name__c = lastName;
	        u.Password__c = pass;
	        u.Name = email;

	        insert u;

	        //u = [select Id,DNI__c,Email__c,First_Name__c,Last_Name__c,Password__c,Name from User__c where Id=:u.Id];	

	        return u;
		}

		public Shop__c fillShop(String name,String description,String logo,String url,String sector,String subCategory){

    		Shop__c s = new Shop__c();
		    s.Name = name;
		    s.Description__c = description;
		    s.URL__c = url;
		    s.Sector__c = sector;
		    s.Sub_Category__c = subCategory;
		    s.Employee_Count_Number__c = 1; 
		    //s.sector = 'sector';
		    //s.subcategory = 'subCategory';	

		    insert s;

		    return s;
		}

		public UserShopJunt__c fillUserShopJunt(User__c user,Shop__c shop){

		    UserShopJunt__c uj = new UserShopJunt__c();
		    uj.User__r = user;
		    uj.Shop__r = shop;
		    uj.Shop__c = shop.Id;
		    uj.User__c = user.Id;

		    insert uj;

		    return uj;
		}    
	}
}