src/objects/Shop__c.object
<CustomObject>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Montevideo/src/objects/Shop__c.object
    <fields>
        <fullName>Logo_Url__c</fullName>
        <label>Logo Url</label>
        <type>Url</type>
    </fields>

Montevideo/src/objects/Shop__c.object
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <type>Url</type>
    </fields>

src/classes/CommerceProfileController.cls
public class CommerceProfileController{
    public List<Shop__c> associatedShops{get;set;}
    public Shop__c currentShop{get;set;}
    public String shopIdChosen {get; set;}
    
    public CommerceProfileController(){
        associatedShops = [SELECT Name, Site__c, Logo_Url__c FROM Shop__c];
   
    }
    public PageReference showCommerce(){
         currentShop = [SELECT Name, Site__c, Logo_Url__c FROM Shop__c WHERE Id = :shopIdChosen]; 
         return null;
    }
}