src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Count_Number__c</fullName>
        <label>Employee Count Number</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Agroindustria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alimento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contrucción</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tecnología</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Sector__c</controllingField>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aereo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marítimo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Lechera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producción Avicola</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Medellin/src/classes/ShopViewController.cls
public class ShopViewController  {

    List<Shop__c> Shops;

    public ShopViewController(){
    }

    public ShopViewController(ApexPages.StandardController controller) {
        Document d = (Document) controller.getRecord();
        d.folderid = UserInfo.getUserId(); //this puts it in My Personal Documents
    }

    public List<Shop__c> getShops() {
        if(Shops == null) {
           Shops = [SELECT Id, Name,Description__c, Sector__c,Sub_Category__c,URL__c,Employee_Count_Number__c,Logo__c FROM Shop__c];
        }
        return Shops;
    }

    public PageReference NewShop() {

        PageReference NewShop = Page.ShopNew;
        NewShop.setRedirect(true);

        return NewShop;
    }

    public PageReference EditShop() {

        String ShopID = Apexpages.currentPage().getParameters().get('ShopId');

        PageReference EditShop = Page.ShopEdit;
        EditShop.setRedirect(true);

        if (ShopID != null)
        {
            EditShop.getParameters().put('id',ShopID);
        }

        return EditShop;
    }

    public PageReference DeleteShop(){

        String ShopID = Apexpages.currentPage().getParameters().get('ShopId');

        PageReference ShopView = Page.ShopView;
        ShopView.setRedirect(true);

        if (ShopID != null)
        {
            Shop__c Shop = [select id, name from Shop__c where id =:ShopID];

            if (Shop != null)
            {
                delete Shop;
            }
        }

        return ShopView;
    }

    public PageReference GoDash(){

        PageReference DashBoard = Page.Dashboard;
        DashBoard.setRedirect(true);

        return DashBoard;
    }
}