src/objects/Shop__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Shop</label>
    <nameField>
        <label>Shop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserShopJunt__c.object
<CustomObject>
    <fields>
        <fullName>Shop__c</fullName>
        <label>Shop</label>
        <referenceTo>Shop__c</referenceTo>
        <relationshipLabel>UserShopJunctions</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>UserRelation</relationshipLabel>
        <relationshipName>UserShopJunctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UserShopJunction</label>
    <nameField>
        <label>UserShopJunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserShopJunctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ComerceListController.cls
public with sharing class ComerceListController {

	public List<Shop__c> shops {get;set;}
	public String redirectUrl{get;set;}
	public boolean shouldRedirect{get;set;}

	public ComerceListController() {
		getShopsByUser();
	}

	public void getShopsByUser(){
		User__c userObject = null;
		
		if(ApexPages.currentPage().getCookies().get('session') != null){						
			ID idSession = ID.valueOf(ApexPages.currentPage().getCookies().get('session').getValue());
			userObject = User.getUserObject(idSession);
			if(userObject != null){
				ID userId = userObject.Id;			
				shops = [SELECT s.Id,s.Logo__c,s.Name,s.Description__c,s.URL__c 
						FROM Shop__c s 
						WHERE s.Id in ( SELECT us.Shop__c	FROM UserShopJunt__c us	WHERE us.User__c = :userId)];				
			}
		}
	}

	public PageReference goToStatistics(){
		String shopID = Apexpages.currentPage().getParameters().get('shopId');	
		redirectUrl = '/apex/ComercePage?shopId=' + shopID;
		shouldRedirect = true;
        return null;		
	}
}