src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>DNI__c</fullName>
        <label>DNI</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Medellin/src/classes/LoginController.cls
public class LoginController {
    
    public String email { get; set; }
    public String password { get; set; }

    public LoginController(){}
    
    public PageReference login() {
        
        //System.debug('************ ingrese con: ************ '+email+' '+password);

        String error = '';

        List<User__c> users = [SELECT u.Email__c,u.Password__c,u.DNI__c,u.Id FROM User__c u WHERE u.Email__c = :email];
        
        if(users == null || users.size()==0){
            error = 'Incorrect user name';                        
        }else{
            
            if(!password.equals(users.get(0).Password__c)) {
                error = 'Password dont match';                
            }
        }

        if(!String.isEmpty(error)){
            
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, error);
            ApexPages.addMessage(msg);
            //System.debug('************ no encontre nada: ************ '+email+' '+password);

        }else{
            
            PageReference page = new PageReference('/apex/Dashboard');
            Cookie userCookie = new Cookie('session', String.valueOf(users.get(0).Id), '/', 1000, false); 

            page.setCookies(new Cookie[] {
                userCookie
            });
    
            page.setRedirect(true);
            //System.debug('************ los datos son correctos '+email+' '+password);
            return page;        

        }

        return null;
    }    
}