src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>User</label>
    <nameField>
        <label>User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ForgotPasswordController.cls
global class ForgotPasswordController {

    public ForgotPasswordController() {
    }
    
    public String email{get; set;}
    
    private User__c findUserByEmail(String userEmail){
      list<User__c>  userList = [SELECT Id, User__c.Email__c, User__c.Password__c FROM User__c WHERE User__c.Email__c = :userEmail.trim()  LIMIT 1]; 
        if(userList != null && userList.size() > 0 ){
           return userList[0];
        } else {
			return null;            
        }

    }
    
    public PageReference sendEmail() {
       User__c user =  findUserByEmail(email);
        if(user  != null){
            doSendEmail(user);
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Please go to your email box account!');
            ApexPages.addMessage(msg);
            return null;
        } else {
         ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The email does not exist!');
            ApexPages.addMessage(msg);   
            return null;
        }
         
         return null;
     }
    
    public void doSendEmail(User__c user) {
           try {

              Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
              OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'ignacio.gonzalez@globant.com'];
              message.setToAddresses(new String[] {
                 user.Email__c
              });

              message.setOrgWideEmailAddressId(owea.get(0).Id);
              message.setEmailPriority('High');
              message.setSubject('Hi this is your password');
              // We can also just use an id for an implicit to address
              message.setPlainTextBody('This is your password ' + user.Password__c);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
           } catch (Exception ce) {
              ce.getMessage();
           }
}
}